### PR TITLE
Create ubuntu-build-docker.yml

### PR DESCRIPTION
**Pull request by wangjingz**

### CODE REVIEW

**Comment by wangjingz** [comment]
Add docker build workflow.

**Review by xiaoxial — APPROVED** [review]
LGTM

**Review by djie1 — APPROVED** [review]
BTW, in this action, it only builds with OV 22.3?

**Comment by wangjingz** [comment]
> BTW, in this action, it only builds with OV 22.3?

Yes, only build OV22.3,  if need OV23.2 , can add another build workflow.

**Pull request merged**
